name: Run SonarQube with Node.js on SonarCloud

on: push

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run SonarQube analysis
      run: npx sonarqube-scanner
      env:
        SONAR_PROJECT_KEY: testsonarqubegorimaaa
        SONAR_ORGANIZATION: TestSonarQubeGorimaaa
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_LOGIN: ${{ secrets.SONARQUBESECRET }}
